# listen on port 80
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.metrics]
    address = ":8899"

# Traefik dashboard over http
[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"

# containers are not discovered automatically
[providers]
  [providers.docker]
    exposedByDefault = false

# enable prometheus
[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels=true
    entryPoint = "metrics"
    buckets = [0.1,0.3,1.2,5.0]
